#!/bin/sh

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
    # Fall back to using the very slow lsb_release utility
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

used_memory=$(free -h | awk '/^Mem:/ {print $3}')
total_memory=$(free -h | awk '/^Mem:/ {print $2}')

used_disk=$(df -h / | awk '/^\/dev/ {print $3}')
total_disk=$(df -h / | awk '/^\/dev/ {print $2}')

printf "             Welcome to %s\n" "$DISTRIB_DESCRIPTION"
echo ""
printf "    [%s %s %s]\n" "$(uname -o)" "$(uname -r)" "$(uname -m)"
printf "        [Memory: %s/%s | Disk: %s/%s]\n" "$used_memory" "$total_memory" "$used_disk" "$total_disk"
echo ""
